### ISSUE TITLE
404 for next routes with nextjs@^6.0.3

### ISSUE THREAD

**Issue by Xiphe** [Vadorequest/serverless-with-next5-boilerplate#10]
When I update next to the latest version, all routes controlled by next return 404 in production mode. dev mode works as expected.

**Comment by Vadorequest** [comment]
Next.js changed the way they start Next apps in v6 and I haven't looked into it so far, so this repo only works for v5 for now.

I won't be looking into it until I actually need it, but if you do and find a way, please make a PR and I'll review/test/merge ASAP. :)

**Comment by Vadorequest** [comment]
@Xiphe https://github.com/zeit/next.js/issues/1406#issuecomment-397495165

**Comment by Xiphe** [comment]
sweet, thanks for the reply.

I used this repo as inspiration, not actually using it, so for me the issue is solved, feel free to close or keep as a reminder for next@6

If I find the time I prepare a PR

**Comment by mitchellhuang** [comment]
@Xiphe here you go bro: https://github.com/mitchellhuang/future

Next.js 6 running on serverless with `serverless-http`.

The change from v5 to v6 is seen here:

https://github.com/mitchellhuang/future/blob/master/server.js#L30
https://github.com/mitchellhuang/future/blob/master/lambda.js#L29

We do an `app.prepare()` before returning our `serverless-http` handler function.

**Comment by jasonkylefrank** [comment]
Did @mitchellhuang's solution work?  Curious if this issue should be closed or if there are other issues that don't work right for next.js apps running on AWS Lambda?

**Comment by Vadorequest** [comment]
Next and aws lambda is a bit complicated to setup, it's not tomething
working out of the box.
In this case, it's not a bug but rather a change in behavior that needs to
be addressed.
