### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wolke** [Vadorequest/serverless-with-next5-boilerplate#3]
Error --------------------------------------------------

  Error: Could not set up basepath mapping. Try running sls create_domain first.
Error: Error: 'swn.dev.vadorequest.fr' could not be found in API Gateway.
NotFoundException: Invalid domain name identifier specified

**Comment by cairesvs** [comment]
You need to change your domain to your domain and create the domain on AWS running `sls create_domain`. This might help you https://serverless.com/framework/docs/providers/aws/guide/credentials/

**Comment by Vadorequest** [comment]
@Wolke I have update the README and opened this issue: https://github.com/Vadorequest/serverless-with-next/issues/5

Let me know on this issue if there is something you don't understand. :)
